"Resource/UI/HudAmmoWeapons.res"
{
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"BM_Space32"
		"fgcolor"		"White"
		"xpos"			"-4"
		"ypos"			"11"
		"zpos"			"7"
		"wide"			"96"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"
		"labelText"		"%Ammo%"
		
	}	
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"			"Blocks48"
		"xpos"			"-9999"
		"ypos"			"-9999"
		"zpos"			"8"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"	
		"labelText"		"%Ammo%"
		
	}		
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"BM_Space16"
		"fgcolor"		"White"
		"xpos"			"92"
		"ypos"			"6"
		"zpos"			"7"
		"wide"			"48"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-west"		
		"labelText"		"%AmmoInReserve%"
	}
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"			"Blocks24"
		"xpos"			"-9999"
		"ypos"			"-9999"
		"zpos"			"8"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"		
		"labelText"		"%AmmoInReserve%"
	}						
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"BM_Space32"
		"fgcolor"		"White"
		"xpos"			"6"
		"ypos"			"11"
		"zpos"			"7"
		"wide"			"144"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south"		
		"labelText"		"%Ammo%"
		
	}	
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
		"font"			"Blocks48"
		"xpos"			"-9999"
		"ypos"			"-9999"
		"zpos"			"8"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"		
		"labelText"		"%Ammo%"
		
	}									
	"AmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"AmmoBG"
		"xpos"			"5"
		"ypos"			"5"
		"zpos"			"4"
		"wide"			"160"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../vgui/replay/thumbnails/white"
        "scaleImage"    "1"
	}
	"AmmoTeamColor"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"AmmoTeamColor"
		"xpos"			"5"
		"ypos"			"5"
		"zpos"			"5"
		"wide"			"160"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../vgui/replay/thumbnails/gray"
        "scaleImage"    "1"
		"teambg_1"		"../vgui/replay/thumbnails/gray"
		"teambg_2"		"../vgui/replay/thumbnails/red"
		"teambg_3"		"../vgui/replay/thumbnails/blue"
	}
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"170"
		"tall"			"60"
		"Alpha"		    "0"
		"Visible"		"0"
		"Enabled"		"1"
        "fillcolor"     "241 44 9 255"
	}
}
