"Resource/UI/HudAmmoWeapons.res"
{
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"VCR_OSD_Mono48"
		"fgcolor"		"MonitorGreen"
		"xpos"			"1"
		"ypos"			"10"
		"zpos"			"9"
		"wide"			"96"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"	
		"labelText"		"%Ammo%"
		
	}	
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"			"Blocks48"
		"fgcolor"		"MonitorDarkGreen"
		"xpos"			"1"
		"ypos"			"10"
		"zpos"			"8"
		"wide"			"96"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"	
		"labelText"		"%Ammo%"
		
	}		
	"AmmoZeros1"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoZeros1"
		"font"			"VCR_OSD_Mono48"
		"fgcolor"		"MonitorGreen"
		"xpos"			"1"
		"ypos"			"10"
		"zpos"			"7"
		"wide"			"96"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-east"	
		"labelText"		"0​0​0"
		
	}						
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"VCR_OSD_Mono24"
		"fgcolor"		"MonitorGreen"
		"xpos"			"97"
		"ypos"			"9"
		"zpos"			"9"
		"wide"			"48"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"		
		"labelText"		"%AmmoInReserve%"
	}
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"			"Blocks24"
		"fgcolor"		"MonitorDarkGreen"
		"xpos"			"97"
		"ypos"			"9"
		"zpos"			"8"
		"wide"			"48"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"		
		"labelText"		"%AmmoInReserve%"
	}												
	"AmmoZeros2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoZeros2"
		"font"			"VCR_OSD_Mono24"
		"fgcolor"		"MonitorGreen"
		"xpos"			"97"
		"ypos"			"9"
		"zpos"			"7"
		"wide"			"48"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-east"		
		"labelText"		"0​0​0"
	}								
	"AmmoZeros3"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoZeros3"
		"font"			"VCR_OSD_Mono24"
		"fgcolor"		"MonitorGreen"
		"xpos"			"97"
		"ypos"			"-11"
		"zpos"			"7"
		"wide"			"48"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-east"		
		"labelText"		"0​0​0"
	}					
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"VCR_OSD_Mono48"
		"fgcolor"		"MonitorGreen"
		"xpos"			"1"
		"ypos"			"10"
		"zpos"			"9"
		"wide"			"96"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"		
		"labelText"		"%Ammo%"
		
	}	
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
		"font"			"Blocks48"
		"fgcolor"		"MonitorDarkGreen"
		"xpos"			"1"
		"ypos"			"10"
		"zpos"			"8"
		"wide"			"96"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"		
		"labelText"		"%Ammo%"
		
	}									
	"AmmoConsoleOutline"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"AmmoConsoleOutline"
		"xpos"			"0"
		"ypos"			"5"
		"zpos"			"4"
		"wide"			"150"
		"tall"			"47"
		"visible"		"1"
		"enabled"		"1"
        "fillcolor"     "MonitorOutline"
	}
	"AmmoGreenColoredConsole"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"AmmoGreenColoredConsole"
		"xpos"			"2"
		"ypos"			"7"
		"zpos"			"5"
		"wide"			"146"
		"tall"			"43"
		"visible"		"1"
		"enabled"		"1"
        "fillcolor"     "MonitorDarkGreen"
	}
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"2"
		"ypos"			"7"
		"zpos"			"6"
		"wide"			"146"
		"tall"			"43"
		"Alpha"		    "0"
		"Visible"		"0"
		"Enabled"		"1"
        "fillcolor"     "MonitorDarkRed"
	}
	"AmmoScanLines"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"AmmoScanLines"
		"xpos"			"2"
		"ypos"			"7"
		"zpos"			"10"
		"wide"			"146"
		"tall"			"43"
		"visible"		"1"
		"enabled"		"1"
        "image"         "../vgui/replay/thumbnails/scanlines"
        "scaleimage"    "1"
	}
}
