"Resource/UI/HudMedicCharge.res"
{	
	"Background"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"Background"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"130"
		"tall"			"65"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/medic_charge_blue_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/medic_charge_red_bg"
		"teambg_3"		"../hud/medic_charge_blue_bg"				
	}
	"UberConsoleOutline"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"UberConsoleOutline"
		"xpos"			"5"
		"ypos"			"5"
		"zpos"			"0"
		"wide"			"150"
		"tall"			"49"
		"visible"		"1"
		"enabled"		"1"
        "fillcolor"     "MonitorOutline"
	}
	"UberGreenColoredConsole"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"UberGreenColoredConsole"
		"xpos"			"7"
		"ypos"			"7"
		"zpos"			"1"
		"wide"			"146"
		"tall"			"45"
		"visible"		"1"
		"enabled"		"1"
        "fillcolor"     "MonitorDarkerGreen"
	}
	"UberConsoleFlash"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"UberConsoleFlash"
		"xpos"			"7"
		"ypos"			"7"
		"zpos"			"2"
		"wide"			"146"
		"tall"			"45"
		"alpha"		    "0"
		"visible"		"1"
		"enabled"		"1"
        "fillcolor"     "MonitorDarkerWhite"
	}
	"UberScanLines"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"UberScanLines"
		"xpos"			"7"
		"ypos"			"7"
		"zpos"			"7"
		"wide"			"146"
		"tall"			"45"
		"visible"		"1"
		"enabled"		"1"
        "image"         "../vgui/replay/thumbnails/scanlines"
        "scaleimage"    "1"
	}
	
	"ChargeLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabel"
		"xpos"			"7"
		"ypos"			"7"
		"zpos"			"6"
		"wide"			"140"
		"tall"			"18"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%charge%%%"
		"textAlignment"	"south-east"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"VCR_OSD_MONO16"
		"fgcolor"		"MonitorGreen"
	}
	"ChargeLabelBG"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabelBG"
		"xpos"			"7"
		"ypos"			"7"
		"zpos"			"5"
		"wide"			"140"
		"tall"			"18"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%charge%%%"
		"textAlignment"	"south-east"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Blocks16"
		"fgcolor"		"MonitorDarkerGreen"
	}
	
	"ChargeLabelZeros"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabelZeros"
		"xpos"			"7"
		"ypos"			"7"
		"zpos"			"4"
		"wide"			"140"
		"tall"			"18"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"ÜBER: 0​0  "
		"textAlignment"	"south-east"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"VCR_OSD_MONO16"
		"fgcolor"		"MonitorGreen"
	}

	"IndividualChargesLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"IndividualChargesLabel"
		"xpos"			"7"
		"ypos"			"7"
		"zpos"			"6"
		"wide"			"130"
		"tall"			"18"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%charge_count%"
		"textAlignment"	"south-east"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"VCR_OSD_MONO16"
		"fgcolor"		"MonitorGreen"
	}
	
	"ChargeMeter"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"			"45"
		"ypos"			"38"
		"zpos"			"4"
		"wide"			"100"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
        "fgcolor_override"       "MonitorGreen"
        "bgcolor_override"       "MonitorDarkGreen"
	}		

	"ChargeMeter1"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter1"
		"font"			"Default"
		"xpos"			"45"
		"ypos"			"38"
		"zpos"			"3"
		"wide"			"100"
		"tall"			"2"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
        "fgcolor_override"       "MonitorGreen"
        "bgcolor_override"       "MonitorDarkGreen"
	}

	"ChargeMeter2"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter2"
		"font"			"Default"
		"xpos"			"45"
		"ypos"			"40"
		"zpos"			"3"
		"wide"			"100"
		"tall"			"2"					
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
        "fgcolor_override"       "MonitorGreen"
        "bgcolor_override"       "MonitorDarkGreen"
	}

	"ChargeMeter3"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter3"
		"font"			"Default"
		"xpos"			"45"
		"ypos"			"42"
		"zpos"			"3"
		"wide"			"100"
		"tall"			"2"					
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
        "fgcolor_override"       "MonitorGreen"
        "bgcolor_override"       "MonitorDarkGreen"
	}

	"ChargeMeter4"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter4"
		"font"			"Default"
		"xpos"			"45"
		"ypos"			"44"
		"zpos"			"3"
		"wide"			"100"
		"tall"			"2"					
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
        "fgcolor_override"       "MonitorGreen"
        "bgcolor_override"       "MonitorDarkGreen"
	}
	"ChargeMeter5"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter5"
		"font"			"Default"
		"xpos"			"45"
		"ypos"			"38"
		"zpos"			"3"
		"wide"			"100"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
        "bgcolor_override"       "MonitorGreen"
	}	
	
	"HealthClusterIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HealthClusterIcon"
		"xpos"			"2"
		"ypos"			"17"
		"wide"			"36"
		"tall"			"36"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/ico_health_cluster"
		"scaleImage"	"1"	
	}	
	"ResistIconAnchor"
	{
		"ControlName"								"Panel"
		"FieldName"									"ResistIconAnchor"
		"XPos"										"25"
		"YPos"										"10"
		"Wide"										"0"
		"Visible"									"1"
		"Enabled"									"1"
		"ProportionalToParent"						"1"
	}
	"ResistIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ResistIcon"
		"xpos"			"0"
		"ypos"			"-25"
		"zpos"			"8"
		"wide"			"36"
		"tall"			"36"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../HUD/defense_buff_bullet_blue"
		"scaleImage"	"1"	

		"Pin_To_Sibling"							"ResistIconAnchor"
		"Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
		"Pin_To_Sibling_Corner"						"PIN_CENTER_TOP"
	}
	
}
